/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAuthzInterface extends Interface {
  getFunction(
    nameOrSignature: "execGrant" | "grant" | "setGrant"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execGrant",
    values: [AddressLike, AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grant",
    values: [AddressLike, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setGrant",
    values: [AddressLike, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "execGrant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grant", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setGrant", data: BytesLike): Result;
}

export interface IAuthz extends BaseContract {
  connect(runner?: ContractRunner | null): IAuthz;
  waitForDeployment(): Promise<this>;

  interface: IAuthzInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  execGrant: TypedContractMethod<
    [
      granter: AddressLike,
      recipient: AddressLike,
      denom: string,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;

  grant: TypedContractMethod<
    [granter: AddressLike, grantee: AddressLike, denom: string],
    [bigint],
    "view"
  >;

  setGrant: TypedContractMethod<
    [grantee: AddressLike, denom: string, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "execGrant"
  ): TypedContractMethod<
    [
      granter: AddressLike,
      recipient: AddressLike,
      denom: string,
      amount: BigNumberish
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "grant"
  ): TypedContractMethod<
    [granter: AddressLike, grantee: AddressLike, denom: string],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setGrant"
  ): TypedContractMethod<
    [grantee: AddressLike, denom: string, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
