/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IJsonInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "extractAsBytes"
      | "extractAsBytesList"
      | "extractAsUint256"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "extractAsBytes",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "extractAsBytesList",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "extractAsUint256",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "extractAsBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extractAsBytesList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extractAsUint256",
    data: BytesLike
  ): Result;
}

export interface IJson extends BaseContract {
  connect(runner?: ContractRunner | null): IJson;
  waitForDeployment(): Promise<this>;

  interface: IJsonInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  extractAsBytes: TypedContractMethod<
    [input: BytesLike, key: string],
    [string],
    "view"
  >;

  extractAsBytesList: TypedContractMethod<
    [input: BytesLike, key: string],
    [string[]],
    "view"
  >;

  extractAsUint256: TypedContractMethod<
    [input: BytesLike, key: string],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "extractAsBytes"
  ): TypedContractMethod<[input: BytesLike, key: string], [string], "view">;
  getFunction(
    nameOrSignature: "extractAsBytesList"
  ): TypedContractMethod<[input: BytesLike, key: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "extractAsUint256"
  ): TypedContractMethod<[input: BytesLike, key: string], [bigint], "view">;

  filters: {};
}
