/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iOraidexPairV2QuerySol from "./IOraidexPairV2Query.sol";
export type { iOraidexPairV2QuerySol };
